[package]
name = "rs_toio_cube"
version = "0.1.0"
authors = ["Kazuhiro.Yabe <Kazuhiro.Yabe@gmail.com>"]
edition = "2018"

[dependencies.winrt]
version = "0.6.0"
features = ["windows-system", "windows-devices", "windows-storage"]
